import { z } from "zod"
import { TRPCError } from "@trpc/server"
import { router, staffProcedure, adminProcedure } from "../trpc"

export const staffRouter = router({
  listHousekeepingStaff: staffProcedure.query(async ({ ctx }) => {
    if (!ctx.propertyId) {
      throw new TRPCError({ code: "BAD_REQUEST", message: "No property in context" })
    }
    return ctx.db.staff.findMany({
      where: { propertyId: ctx.propertyId, role: "HOUSEKEEPING", isActive: true },
      select: { id: true, firstName: true, lastName: true },
      orderBy: [{ firstName: "asc" }, { lastName: "asc" }],
    })
  }),

  list: adminProcedure.query(async ({ ctx }) => {
    if (!ctx.propertyId) {
      throw new TRPCError({ code: "BAD_REQUEST", message: "No property in context" })
    }
    return ctx.db.staff.findMany({
      where: { propertyId: ctx.propertyId },
      select: {
        id: true,
        firstName: true,
        lastName: true,
        email: true,
        role: true,
        isActive: true,
        lastLoginAt: true,
        createdAt: true,
      },
      orderBy: [{ role: "asc" }, { firstName: "asc" }],
    })
  }),

  // passwordHash must be generated by the caller (bcrypt, cost 12)
  create: adminProcedure
    .input(
      z.object({
        firstName: z.string().min(1).max(100),
        lastName: z.string().min(1).max(100),
        email: z.string().email(),
        role: z.enum(["ADMIN", "MANAGER", "FRONT_DESK", "HOUSEKEEPING", "ACCOUNTANT"]),
        passwordHash: z.string().min(10),
      })
    )
    .mutation(async ({ ctx, input }) => {
      if (!ctx.propertyId) {
        throw new TRPCError({ code: "BAD_REQUEST", message: "No property in context" })
      }

      const existing = await ctx.db.staff.findUnique({
        where: { email: input.email.toLowerCase() },
      })
      if (existing) {
        throw new TRPCError({ code: "CONFLICT", message: "Email already in use" })
      }

      const staff = await ctx.db.staff.create({
        data: {
          propertyId: ctx.propertyId,
          firstName: input.firstName,
          lastName: input.lastName,
          email: input.email.toLowerCase(),
          role: input.role,
          passwordHash: input.passwordHash,
        },
        select: {
          id: true,
          firstName: true,
          lastName: true,
          email: true,
          role: true,
          isActive: true,
          createdAt: true,
        },
      })

      await ctx.db.auditLog.create({
        data: {
          staffId: ctx.auth.staffId,
          entityType: "Staff",
          entityId: staff.id,
          action: "CREATE",
          changes: { email: staff.email, role: staff.role },
        },
      })

      return staff
    }),

  updateRole: adminProcedure
    .input(
      z.object({
        id: z.string(),
        role: z.enum(["ADMIN", "MANAGER", "FRONT_DESK", "HOUSEKEEPING", "ACCOUNTANT"]),
      })
    )
    .mutation(async ({ ctx, input }) => {
      if (!ctx.propertyId) {
        throw new TRPCError({ code: "BAD_REQUEST", message: "No property in context" })
      }
      if (input.id === ctx.auth.staffId) {
        throw new TRPCError({ code: "BAD_REQUEST", message: "Cannot change your own role" })
      }

      const staff = await ctx.db.staff.findFirst({
        where: { id: input.id, propertyId: ctx.propertyId },
      })
      if (!staff) throw new TRPCError({ code: "NOT_FOUND", message: "Staff not found" })

      const updated = await ctx.db.staff.update({
        where: { id: input.id },
        data: { role: input.role },
        select: { id: true, firstName: true, lastName: true, email: true, role: true, isActive: true },
      })

      await ctx.db.auditLog.create({
        data: {
          staffId: ctx.auth.staffId,
          entityType: "Staff",
          entityId: input.id,
          action: "UPDATE",
          changes: { previousRole: staff.role, newRole: input.role },
        },
      })

      return updated
    }),

  deactivate: adminProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      if (!ctx.propertyId) {
        throw new TRPCError({ code: "BAD_REQUEST", message: "No property in context" })
      }
      if (input.id === ctx.auth.staffId) {
        throw new TRPCError({ code: "BAD_REQUEST", message: "Cannot deactivate yourself" })
      }

      const staff = await ctx.db.staff.findFirst({
        where: { id: input.id, propertyId: ctx.propertyId },
      })
      if (!staff) throw new TRPCError({ code: "NOT_FOUND", message: "Staff not found" })

      const updated = await ctx.db.staff.update({
        where: { id: input.id },
        data: { isActive: !staff.isActive },
        select: { id: true, firstName: true, lastName: true, email: true, role: true, isActive: true },
      })

      await ctx.db.auditLog.create({
        data: {
          staffId: ctx.auth.staffId,
          entityType: "Staff",
          entityId: input.id,
          action: updated.isActive ? "ACTIVATE" : "DEACTIVATE",
          changes: { isActive: updated.isActive },
        },
      })

      return updated
    }),
})
